Improved authserver script
git-svn-id: https://suckerserv.googlecode.com/svn/trunk@41 32555feb-acdc-9533-d4e0-d00e80c872cf

diff --git a/bin/authserver b/bin/authserver
--- a/bin/authserver
+++ b/bin/authserver
@@ -81,13 +81,13 @@ p_start() {
     
     ERROR_START=$(( $ERROR_START + 1 ))
     
-    # start the game server as a background process
-    nohup bin/sauer_authserver ${AUTHSERVER_OPTIONS} 1>log/authstatus.log 2>>log/autherror.log </dev/null &
+    # start the auth server as a background process
+    nohup bin/monitor bin/sauer_authserver ${AUTHSERVER_OPTIONS} 1>log/authstatus.log 2>>log/autherror.log </dev/null &
     
-    #wait for server to start up and print the initial status messages
+    # wait for auth server to start up and print the initial status messages
     until $(cat log/authstatus.log | grep -q *READY*)
     do
-        #stop if server has terminated
+        #stop if auth server has terminated
         jobs %- > /dev/null 2>&1
         RUNNING=$?
         if [ "$RUNNING" = "1" ]
@@ -101,7 +101,7 @@ p_start() {
     
     if [ "$v_remove_status_log" = "y" ]
     then
-	rm log/authstatus.log
+        rm log/authstatus.log
     fi
     
     return 0
@@ -111,10 +111,17 @@ p_stop() {
 
     if ! p_exec shutdown
     then
-	return 1
+        return 1
     fi
-    
+
     return 0
+}
+
+p_restart() {
+
+    p_stop
+    sleep 2
+    p_start
 }
 
 ################################################################################
@@ -179,207 +186,219 @@ p_help() {
 
 case "$1" in
     'start')
-	case "$2" in
-	    'luapp')
+	    case "$2" in
+	        'luapp')
                 if [ "x$3" = "x" ]
                 then
                     p_help
+                    echo "No file given."
+                    echo "usage: $0 start luapp luafile"
                     exit 2
                 fi
                 
                 shift 2
                 p_luapp "$*"
-            ;;
+                ;;
             *)
-        	if [ "x$2" = "x--no-statuslog" ]
-		then
-		    v_remove_status_log=y
-		fi
+                if [ "x$2" = "x--no-statuslog" ]
+	            then
+	                v_remove_status_log=y
+                fi
+
+                if [ ! -x bin/sauer_authserver ]
+                then
+                    echo "Cannot find or execute bin/sauer_authserver"
+                    exit 1
+                fi
+        
+                if [ ! -x bin/monitor ]
+                then
+                    echo "Cannot find or execute bin/monitor"
+                    exit 1
+                fi
 		
-    		if ! p_start
-    		then
-    		    echo "It appears the auth server is already running."
-    		fi
-	    ;;
-	esac
-    ;;
+        		if ! p_start
+        		then
+        		    echo "It appears the auth server is already running."
+        		fi
+	            ;;
+	    esac
+        ;;
     'stop')
         p_stop
-    ;;
+        ;;
     'restart')
-	p_stop
-	sleep 1
-	p_start
-    ;;
+        p_restart
+        ;;
     'manage')
-	case "$2" in
-	    'generate'|'gen')
-		p_keygen
-    	    ;;
+        case "$2" in
+	        'generate'|'gen')
+	        	p_keygen
+    	        ;;
             'key')
-        	exec $d_main/bin/$f_starter manage generate key
-    	    ;;
-	    'user')
-		case "$3" in
-		    'add')
-			if [ "x$6" = "x" ] || [ "x$5" = "x" ] || [ "x$4" = "x" ]
-			then
-			    p_help
-			    exit 2
-			fi
+            	exec $d_main/bin/$f_starter manage generate key
+        	    ;;
+	        'user')
+	        	case "$3" in
+	        	    'add')
+	        	    	if [ "x$6" = "x" ] || [ "x$5" = "x" ] || [ "x$4" = "x" ]
+	        	    	then
+	        	    	    p_help
+	        	    	    exit 2
+	        	    	fi
+	    		
+	    	        	p_exec "add_user \"$4\" \"$5\" \"$6\""
+	            	    ;;
+		            'del')
+		            	if [ "x$5" = "x" ] || [ "x$4" = "x" ]
+	        	    	then
+	        	    	    p_help
+	        	    	    exit 2
+	            		fi
 			
-			p_exec "add_user \"$4\" \"$5\" \"$6\""
-		    ;;
-		    'del')
-			if [ "x$5" = "x" ] || [ "x$4" = "x" ]
-			then
-			    p_help
-			    exit 2
-			fi
+		            	p_exec "del_user \"$4\" \"$5\""
+		                ;;
+		            'change')
+	            		case "$4" in
+	            		    'name')
+		            	    	if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
+		            	    	then
+		            	    	    p_help
+		            	    	    exit 2
+		                		fi
+				
+		            	    	p_exec "change_user_name \"$5\" \"$6\" \"$7\""
+		            	        ;;
+		            	    'key')
+		                		if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
+		            	    	then
+	        			            p_help
+	        			            exit 2
+	        		        	fi
+				
+		        	        	p_exec "change_user_key \"$5\" \"$6\" \"$7\""
+		                	    ;;
+		            	    'domain')
+		                		if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
+		                		then
+	            	    		    p_help
+		                		    exit 2
+		                		fi
+				
+		                		p_exec "change_user_domain \"$5\" \"$6\" \"$7\""
+			                    ;;
+		        	        *)
+			                	p_help
+			                	exit 2
+			                    ;;
+			            esac
+		                ;;
+		            *)
+		            	p_help
+		            	exit 2
+		                ;;
+	        	esac
+	            ;;
+	        'domain')
+	        	case "$3" in
+	        	    'add')
+	            		if [ "x$4" = "x" ]
+	            		then
+                            p_help
+		            	    exit 2
+		            	fi
 			
-			p_exec "del_user \"$4\" \"$5\""
-		    ;;
-		    'change')
-			case "$4" in
-			    'name')
-				if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
-				then
-				    p_help
-				    exit 2
-				fi
-				
-				p_exec "change_user_name \"$5\" \"$6\" \"$7\""
-			    ;;
-			    'key')
-				if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
-				then
-				    p_help
-				    exit 2
-				fi
-				
-				p_exec "change_user_key \"$5\" \"$6\" \"$7\""
-			    ;;
-			    'domain')
-				if [ "x$7" = "x" ] || [ "x$6" = "x" ] || [ "x$5" = "x" ]
-				then
-				    p_help
-				    exit 2
-				fi
-				
-				p_exec "change_user_domain \"$5\" \"$6\" \"$7\""
-			    ;;
-			    *)
-				p_help
-				exit 2
-			    ;;
-			esac
-		    ;;
-		    *)
-			p_help
-			exit 2
-		    ;;
-		esac
-	    ;;
-	    'domain')
-		case "$3" in
-		    'add')
-			if [ "x$4" = "x" ]
-			then
-			    p_help
-			    exit 2
-			fi
+		            	if [ ! "x$5" = "x" ]
+	            		then
+	        	    	    p_exec "add_domain \"$4\" \"$5\""
+	        	    	else
+	        	    	    p_exec "add_domain \"$4\""
+	        	    	fi
+	        	        ;;
+		            'del')
+		            	if [ "x$4" = "x" ]
+		            	then
+		            	    p_help
+		            	    exit 2
+		            	fi
 			
-			if [ ! "x$5" = "x" ]
-			then
-			    p_exec "add_domain \"$4\" \"$5\""
-			else
-			    p_exec "add_domain \"$4\""
-			fi
-		    ;;
-		    'del')
-			if [ "x$4" = "x" ]
-			then
-			    p_help
-			    exit 2
-			fi
-			
-			p_exec "del_domain \"$4\""
-		    ;;
-		    'change')
-			case "$4" in
-			    'name')
-				if [ "x$6" = "x" ] || [ "x$5" = "x" ]
-				then
-				    p_help
-				    exit 2
-				fi
+		            	p_exec "del_domain \"$4\""
+		                ;;
+		            'change')
+		            	case "$4" in
+		            	    'name')
+			                	if [ "x$6" = "x" ] || [ "x$5" = "x" ]
+			                	then
+			                	    p_help
+			                	    exit 2
+			            	    fi
 				
-				p_exec "change_domain_name \"$5\" \"$6\""
-			    ;;
-			    'sensitivity')
-				if [ "x$5" = "x" ]
-				then
-				    p_help
-				    exit 2
-				fi
+    			            	p_exec "change_domain_name \"$5\" \"$6\""
+	    		                ;;
+		    	            'sensitivity')
+			                	if [ "x$5" = "x" ]
+			                	then
+			                	    p_help
+			                	    exit 2
+		            		    fi
 				
-				if [ ! "x$6" = "x" ]
-				then
-				    p_exec "change_domain_sensitivity \"$5\" \"$6\""
-				else
-				    p_exec "change_domain_sensitivity \"$4\""
-				fi
-			    ;;
-			    *)
-				p_help
-				exit 2
-			    ;;
-			esac
-		    ;;
-		    *)
-			p_help
-			exit 2
-		    ;;
-		esac
-	    ;;
-	    'list')
-		case "$3" in
-		    'domains')
-			p_exec "list_domains"
-		    ;;
-		    'users')
-			if [ "x$4" = "x" ]
-			then
-			    p_help
-			    exit 2
-			fi
+    		            		if [ ! "x$6" = "x" ]
+	    		            	then
+		                		    p_exec "change_domain_sensitivity \"$5\" \"$6\""
+		                		else
+		                		    p_exec "change_domain_sensitivity \"$4\""
+		                		fi
+		            	        ;;
+    		        	    *)
+	    		            	p_help
+		    	            	exit 2
+		                	    ;;
+		                esac
+		                ;;
+		            *)
+		            	p_help
+		            	exit 2
+		                ;;
+		        esac
+	            ;;
+	        'list')
+		        case "$3" in
+		            'domains')
+		            	p_exec "list_domains"
+		                ;;
+		            'users')
+	            		if [ "x$4" = "x" ]
+		            	then
+		            	    p_help
+		            	    exit 2
+		            	fi
 			
-			p_exec "list_users \"$4\""
-		    ;;
-		    *)
-			p_help
-			exit 2
-		    ;;
-		esac
-	    ;;
-	    *)
-		p_help
-		exit 2
-	    ;;
-	esac
-    ;;
+		            	p_exec "list_users \"$4\""
+		                ;;
+		            *)
+		            	p_help
+		            	exit 2
+	    	            ;;
+		        esac
+	            ;;
+	        *)
+	        	p_help
+	        	exit 2
+	            ;;
+	    esac
+        ;;
     'convert')
-	p_convert "$2" "$3" "$4" "$5" "$6"
-    ;;
-    'help')
-	p_help
-    ;;
+	   p_convert "$2" "$3" "$4" "$5" "$6"
+        ;;
+     'help')
+	    p_help
+        ;;
     '--no-statuslog')
-	exec $d_main/bin/$f_starter start $*
-    ;;
+        exec $d_main/bin/$f_starter start $*
+        ;;
     *)
-	exec $d_main/bin/$f_starter start $*
-    ;;
+	    exec $d_main/bin/$f_starter start $*
+        ;;
 esac
 
 exit 0
